### ISSUE TITLE
Keyboard handling

### ISSUE THREAD

**Issue by amorenew** [apasccon/SearchTextField#1]
Hi
i have a problem with this textfield and keyboard handling
here i used a popular keyboard handling library but **next and back button** with two SearchTextFileds doesn't work
https://github.com/hackiftekhar/IQKeyboardManager

**Comment by apasccon** [comment]
@amorenew can you please try adding this line of code to your AppDelegate?:

`IQKeyboardManager.sharedManager().toolbarManageBehaviour = .ByTag`

In the meantime I'll try to find out why IQKeyboardManager is not working well with SearchTextFields as subviews.

Thanks!

**Comment by amorenew** [comment]
your solution is worked
thanks a lot.
