### ISSUE TITLE
Search TextFields showing just 5 results in list 

### ISSUE THREAD

**Issue by usman1057** [apasccon/SearchTextField#109]
Search TextFields showing just 5 results in list but when a select one of them it will display accurate result from array on selected index... just showing only 5

**Comment by apasccon** [comment]
Hi @usman1057, can you please give me more details?, the piece of code you are writing, the desired result and the actual one?. Thanks!

**Comment by xhidnoda** [comment]
check in your code this:  
// Set the max number of results. By default it's not limited
mySearchTextField.maxNumberOfResults = 5
