### ISSUE TITLE
Hit Return Key when textfield is not empty will clear the content of the textfield

### ISSUE THREAD

**Issue by chengsam** [apasccon/SearchTextField#11]
If I am typing with the tableview showing, the first filtered result will be chosen and put into the textfield if I hit return key. However, if I click the textfield again without typing and hit the return key. Since there are no filtered results, the following method will produce empty string and the existing content of the textfield will be cleared.

```
open func textFieldDidEndEditingOnExit() {
        self.text = filteredResults.first?.title
}
```

**Comment by apasccon** [comment]
@chengsam it was fixed in 1.0.4. Feel free to test it. Thanks!
