### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=2, address=0x1064b2e58)

### ISSUE THREAD

**Issue by hokage4** [apasccon/SearchTextField#113]
Hi,
when i run my project i get this Error 
"Thread 1: EXC_BAD_ACCESS (code=2, address=0x1064b2e58)"

and my code is
`class provider: UIViewController {
    
    @IBOutlet weak var mySearchTextField: SearchTextField!
    
   
    override func viewDidLoad() {
        super.viewDidLoad()
      
     
        mySearchTextField.filterStrings(["Red", "Blue", "Yellow"])
    }
    `

**Comment by rajkumar0143** [comment]
Hi,
this is your question .........
@IBOutlet weak var mySearchTextField: SearchTextField!


override func viewDidLoad() {
    super.viewDidLoad()
  
 
    mySearchTextField.filterStrings(["Red", "Blue", "Yellow"])
}

I got the solutions 
click textField then add class name  = SearchTextField.swift

![screen shot 2018-04-13 at 3 15 13 pm](https://user-images.githubusercontent.com/35296341/38728451-8dd902f4-3f2d-11e8-9b35-228d41025a28.png)

**Comment by xhidnoda** [comment]
please...close this.
