### ISSUE TITLE
results appearing if I set text on textfield

### ISSUE THREAD

**Issue by deanezra** [apasccon/SearchTextField#13]
If I programmatically set the text on the text field, I am finding that the filtered list of matching results appear below the text field. 

Is there a way to stop the list appearing when text is set programmatically?

ps love the control - and great work.

**Comment by Adarkas2302** [comment]
I don't think there is a way in this project, currently. You might have to hide the tableView your self at the moment.

**Comment by apasccon** [comment]
@deanezra, finally fixed in 1.0.5. If you want to still showing the results when you set the text programmatically, you must set startVisible to true.
