### ISSUE TITLE
results tableView height is too big

### ISSUE THREAD

**Issue by alshcompiler** [apasccon/SearchTextField#134]
the results i am showing are + 20 search results and the tableView is not within the superview so i can't scroll the tableView till the bottom, and in documentation you said maxResultsListHeight can set the max tableView height but it seems you removed it from source code and the tableView is private, so simply you gave me no workaround, please advise

**Comment by apasccon** [comment]
maxResultsListHeight was not removed and it's declared open. Are you using the last version of the code?
