### ISSUE TITLE
property placeholder textColor 

### ISSUE THREAD

**Issue by resand** [apasccon/SearchTextField#16]
How to change the placeholder property **textColor** of the **placeholder** if it is as **fileprivate**, this requires it to change the color of the field when I make field validations.

**Comment by apasccon** [comment]
Have you seen the SearchTextFieldTheme option?. There you have a fontColor. Is that enough?. Are you needing something different?. Thanks for asking and sorry for my response delay.

**Comment by resand** [comment]
Yes, only in this case I needed the placeholder property :\

**Comment by apasccon** [comment]
Please take a look at the 1.0.10 version, you can now set the placeholder color (for both, inline an list options):
```
yourSearchTextField.theme.placeholderColor = UIColor.red
```
