### ISSUE TITLE
how to detecting that user is typing?

### ISSUE THREAD

**Issue by abrahamkj** [apasccon/SearchTextField#161]

**Comment by abrahamkj** [comment]
I got the answer. We can use textFieldDidChange()

**Comment by JHHMobile** [comment]
Can you share how to implement that method? Thanks

**Comment by abrahamkj** [comment]
textfield.addTarget(self, action: #selector(functionname), for: .editingChanged)

func functionname()
{
}

**Comment by abrahamkj** [comment]
textfield.addTarget(self, action: #selector(functionname), for: .editingChanged)

func functionname()
{
}

**Comment by voldzi** [comment]
Ads selector doesn't work as self.text = filteredResults[(indexPath as NSIndexPath).row].title doesn't fired event "editingChanged" (line 600)
Solution is to add line below mentioned line: self.sendActions(for: .editingChanged) 
...it will be nice to add it to master...
