### ISSUE TITLE
Inline mode is broken when text is not left-aligned

### ISSUE THREAD

**Issue by Andreaaa** [apasccon/SearchTextField#26]
The inline suggestion text is always left-aligned, regardless of the alignment of the textview.

This leads to broken results, such as this:
<img width="252" alt="screen shot 2017-03-06 at 14 32 14" src="https://cloud.githubusercontent.com/assets/6324933/23611973/bcaa6d08-0279-11e7-8675-a68c504b70cc.png">

**Comment by apasccon** [comment]
Good catch!. Fixed in 1.0.9. Thanks for reporting it.

**Comment by Andreaaa** [comment]
Very quick and helpful, thanks a lot!
