### ISSUE TITLE
Dropdown not appearing on newest version

### ISSUE THREAD

**Issue by davidthurman** [apasccon/SearchTextField#28]
Hey great framework here. I was testing the version you released yesterday. The dropdown with options does not seem to appear anymore. I implemented the simple example and also pulled down and ran your example project and no dice. The new feature "show the first matched result as placeholder (inline mode)" works great though.

**Comment by apasccon** [comment]
Can you please test the newest 1.0.10 version?. Thanks!.

**Comment by davidthurman** [comment]
<img width="313" alt="screen shot 2017-03-08 at 8 47 22 am" src="https://cloud.githubusercontent.com/assets/14813398/23706393/f5778572-03db-11e7-94df-ab0ad3924814.png">

So when I pull it down and run the example code, whenever I type anything in and wait, nothing will appear for suggestions

**Comment by apasccon** [comment]
It doesn't show nothing since your keyboard is hidden. Please show it with Command + K

**Comment by davidthurman** [comment]
Oh wow I never thought of that! Thank you for the quick help!

**Comment by davidthurman** [comment]
So I am still running into some issues with the table view not displaying. I have the keyboard up on my app. I am adding the Label to a scrollview. It seems like the tableview is not getting called to update. I am not using Pods so I added the SearchTextField class to my project. If you can think of any reason for it not working, please let me know. Thanks for the help!
<img width="237" alt="screen shot 2017-03-09 at 9 57 47 am" src="https://cloud.githubusercontent.com/assets/14813398/23755687/32468ca4-04af-11e7-8bf8-c8c356b9d8f4.png">
<img width="543" alt="screen shot 2017-03-09 at 9 59 46 am" src="https://cloud.githubusercontent.com/assets/14813398/23755697/37ad5a6a-04af-11e7-9c91-89131d5f204d.png">

**Comment by apasccon** [comment]
You are setting "inlineMode" in true....but you want to show the items as a drop-down list right?. So you should remove that. You can also simplify your code using 
```
mySearchTextField.filterStrings(["red", "room", "blue", "black", "green"])
```
instead of 
```
let item1 = ...
let item2 = ...
mySearchTextField.filterItems([item1, item2,...])
```

**Comment by davidthurman** [comment]
Of course it would be something that simple! Thanks a lot for the help
