### ISSUE TITLE
Suggestions not showing at all!

### ISSUE THREAD

**Issue by dvertovsek** [apasccon/SearchTextField#33]
I downloaded the example project, and the country and acronym suggestions are not showing at all.
Only the inline suggestions are working. Maybe you messed the working part when you added the inline feature
Your project is really cool, I would really like to use it, so if you could please look into it.
Thanks in advance

**Comment by apasccon** [comment]
Are you sure that the keyboard is being shown?. Please if you are using the simulator double check it. If the keyboard is not shown, just press Cmd + K. Let me know if it helps.

**Comment by dvertovsek** [comment]
thanks, that was the problem!
