### ISSUE TITLE
Get the filtered results

### ISSUE THREAD

**Issue by MeetaB** [apasccon/SearchTextField#38]
Is there a way to get filtered results? 
In the itemSelectionHandler, I get position and item. But the position is as per the filtered list & not the original list. Here filtered list means the list which is formed after the user enters a character on the textfield and original list means the list of items supplied to the textfield for filtering.

Please help with the above issue.

**Comment by apasccon** [comment]
You'll find it in the new 1.1.2 version. Thanks!
