### ISSUE TITLE
Swift 3 Migration

### ISSUE THREAD

**Issue by sahilparikh98** [apasccon/SearchTextField#4]
Are there any plans to update to swift 3 for Xcode 8 support??

**Comment by apasccon** [comment]
@sahilparikh98, yes, I'll migrate it soon. Thanks for asking.

**Comment by apasccon** [comment]
@sahilparikh98, the release v1.0.2 now supports Swift 3 and Xcode 8. Can you please try it?. Thanks!.

**Comment by sahilparikh98** [comment]
Awesome thank you!! I'll try it and let you know how it goes.

Sahil

**Comment by Adarkas2302** [comment]
Seems to work fine thanks!
