### ISSUE TITLE
Question: Any way to force suggestion without typing?

### ISSUE THREAD

**Issue by trr-amsiq** [apasccon/SearchTextField#41]

**Comment by apasccon** [comment]
Is it related to https://github.com/apasccon/SearchTextField/issues/39?

**Comment by trr-amsiq** [comment]
No just want to show suggestions received from a server and show them directly

**Comment by apasccon** [comment]
Have you tried with startVisible = true?

**Comment by trr-amsiq** [comment]
It does not work
filterStrings is set after view has been initialised

**Comment by apasccon** [comment]
Can you please explain better the scenario?.

If you set startVisible in true, and then you set the filterStrings, as soon as your text field get focus the list of suggestions will appear.

If you are expecting a different behavior please explain it in detail so I can understand what's happening in your code.

**Comment by trr-amsiq** [comment]
I'll try:

In view did load I call
`self.inputField.startVisible = true`

In a callback from a server I get 1 suggestion
`self.inputField.filterStrings([suggestion])`

But nothing shows up

**Comment by apasccon** [comment]
It will appear after the user makes focus over the text field. Just for your reference, it happens after the event .editingDidBegin is fired.
Does it help?

**Comment by trr-amsiq** [comment]
I need it to show without input from the user.
Tried with becomeFirstResponder() no luck

**Comment by trr-amsiq** [comment]
self.inputField.text? += ""

does the trick but is a bit hacky

**Comment by apasccon** [comment]
Hey @trr-amsiq, can you please take a look at the new 1.1.5 version?. I added the property startVisibleWithoutInteraction so the list of results can be shown asap. Thanks!.
