### ISSUE TITLE
Manually add file, syntax errors

### ISSUE THREAD

**Issue by feliciaf** [apasccon/SearchTextField#46]
Hi,

Has anyone by any chance , had seen errors for the SearchTextField.swift errors.
When i drag to project, it gives me syntax errors of the file. ANy help would be really appreciated.

**Comment by apasccon** [comment]
Sorry for my answer delay!. Probably it's because you are using the new Xcode beta (and swift 4).
You can try with the "swift4" branch, which is compatible with Xcode 9 and Swift 4: https://github.com/apasccon/SearchTextField/tree/swift4
