### ISSUE TITLE
received thread error EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by yv2link** [apasccon/SearchTextField#48]
to reproduce:

opened new Xcode project
installed pod ver 1.0.10

code in view controller:

import UIKit
import SearchTextField

class ViewController: UIViewController {

    @IBOutlet weak var mySearchTextField: SearchTextField!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
       
        
        // Set the array of strings you want to suggest
        mySearchTextField.filterStrings(["Red", "Blue", "Yellow"])
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

**Comment by yv2link** [comment]
also tried with version 1.1.2

**Comment by SpaceDivePro** [comment]
I am having the same issue, anyone got any ideas?

**Comment by apasccon** [comment]
It's cause you are not setting your UITextField's class in the Storyboard to "SearchTextField" (take a look at the attached image).
<img width="261" alt="screenshot 2017-07-21 17 10 54" src="https://user-images.githubusercontent.com/2911931/28480598-cadf687c-6e37-11e7-9c84-437eff69e761.png">

**Comment by malokuS** [comment]
This error is back with the new version 1.1.3.

How to reproduce:
1. Install manually:
    - Download SearchTextField.swift
    - Paste into project

2. Link to ViewController
    - `@IBOutlet weak var customSearchTextField: SearchTextField!`

3. Set data source
    - `customSearchTextField.filterStrings(friends)`
4. The UITextField's class is set as you provided on previous solution:
    - <img width="262" alt="screen shot 2017-07-26 at 14 57 59" src="https://user-images.githubusercontent.com/12096589/28621983-19c28f94-7213-11e7-87ea-ba5d8bbc4943.png">

**Comment by apasccon** [comment]
Can you please bring me more details (I can't reproduce)?
- Xcode version
- Simulator / Device you are testing on
- More code to read (ie. how are you filling your "friends" array)

Thanks.

**Comment by malokuS** [comment]
First of all, thank you for your quick reply!

Hmm weird, then I must be doing something wrong(bear with me because I'm a newbie in swift).

Extra details:

-  Xcode version: Version 8.3.3 (8E3004b)
-  Simulator: iPhone 7 - iOS 10.3 (14E8301)
-  The code which I fill my "friends" array (Even though the error is occurring in a previous row):
   
```
fileprivate func configureSimpleSearchTextField() {
        // Start visible - Default: false
        friendSearchTextField.startVisible = true // Error occurs on this line
        
        // Set data source
        let friends = dummyFriends()
        friendSearchTextField.filterStrings(friends)
    }

    /* .... */

    fileprivate func dummyFriends() -> [String] {
        var friendNames = [String]()
        
        friendNames.append("Dumb")
        friendNames.append("And Dumber")
        return friendNames
    }
```

**Comment by apasccon** [comment]
Ok, your code is working well....I'm pretty sure you didn't connect your UITextField with your IBOutlet, did you?

**Comment by malokuS** [comment]
I actually did:

```
class MainViewController: UIViewController, UITextFieldDelegate {
    
    @IBOutlet weak var friendSearchTextField: SearchTextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        configureSimpleSearchTextField()
    }
```

I'm following your example on this repository. Could it be something with the installation method?

**Comment by apasccon** [comment]
Have you connected your friendSearchTextField with your UITextField in your Storyboard?

**Comment by malokuS** [comment]
Yup, this line `@IBOutlet weak var friendSearchTextField: SearchTextField!` was autogenerated after I dragged with ctrl click into my MainViewController.

**Comment by malokuS** [comment]
Okay I gave up on the "Manual Installation" and got it working via Cocoapods.
Thanks for your support @apasccon , keep up the good work!

**Comment by Okeanoo** [comment]
I'm running into the same issue using Cooapods. 

Xcode 9.1
IBOutlet and UITextField are connected.

import UIKit
import SearchTextField


class ViewController: UIViewController, UITextFieldDelegate {

    
    @IBOutlet weak var textField: SearchTextField!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        textField.delegate = self
        
        textField.filterStrings(["One", "Two", "Three"])
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

The Error code is "Thread 1: EXC_BAD_ACCESS (code=2, address= "some address")", and it's at the setup of filterStrings.
