### ISSUE TITLE
Suggestion: when startVisible=true, show full list if user clears the field

### ISSUE THREAD

**Issue by btanner** [apasccon/SearchTextField#51]
I have been playing with your code, which works fantastic by the way.

I *really* want my users to choose from a list, but I want them to be able to override if they really need to, and filter quickly.  So, I load up a large list of options and use startVisible=true and all is grand.

However, if they type a few things and then erase back to blank, your current implementation does not reload the list.

Just needed to make 1 small change to make this work:
```
if text!.isEmpty {
            clearResults()
            tableView?.reloadData()
            self.placeholderLabel?.text = ""
        }
```

Change to:
```
if text!.isEmpty {
            clearResults()
            tableView?.reloadData()
            filter(true)
            self.placeholderLabel?.text = ""
        }
```

I'm not sure if this creates other problems, but it seems to work for me!

**Comment by apasccon** [comment]
Fixed in 1.1.3. Thanks!.
