### ISSUE TITLE
Hide keyboard but show list

### ISSUE THREAD

**Issue by Sk8er22** [apasccon/SearchTextField#53]
Hello guys and thanks for your work...

I need to doesn't´t show the keyboard ontap, so only display the list... I try it delegating 

extension X: UITextFieldDelegate {
    func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        return false
    }

but doesn't works, just no appear nothing, no list (startvisible = true)

Any idea? Thanks!

**Comment by swiftylondon** [comment]
Would like to see this feature added too.

**Comment by apasccon** [comment]
Hey @Sk8er22, @swiftylondon, can you please take a look at the new 1.1.5 version?. I added the property startVisibleWithoutInteraction so the list of results can be shown asap. Thanks!.
