### ISSUE TITLE
Could not change theme font

### ISSUE THREAD

**Issue by arashetm** [apasccon/SearchTextField#54]
In SearchTextFieldTheme we can't set custom font
For example when I use UIFont(name: "BNazanin", size: 10)! in init of SearchTextFieldTheme the tableview does not appear for suggestion

**Comment by apasccon** [comment]
I tested it and it's working. Are you sure you are following the right steps for using custom fonts in your app?. Here you have a good tutorial about it: http://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/#addfontstoplist

**Comment by arashetm** [comment]
Thanks
Successfully added and works !
But I found something else
Suggestion tableview does not appear in iPhone 5 in simulator
(I didn't check in real device)

**Comment by apasccon** [comment]
Good to know you could fix it!.
Regarding simulator please double check that the keyboard is being shown (if not force to show it).

**Comment by arashetm** [comment]
so sry
It works
I don't know why that wasn't working
I have a question
How could I move suggestion strings to right I mean in right to left languages we should start from right

**Comment by apasccon** [comment]
In fact right now it's not supporting RTL languages and it's a good suggestion. Thanks for that I'll implement it soon.

**Comment by arashetm** [comment]
Is there anyway that I can do on my own to implement RTL ?

**Comment by apasccon** [comment]
Please take a look at the new version 1.1.4, it already supports RTL (forceRightToLeft property).
