### ISSUE TITLE
Suggestions do not show up in Simulator

### ISSUE THREAD

**Issue by DarkTerbear** [apasccon/SearchTextField#56]
Inline suggestions work fine, but the dropdown does not work in the simulator.
Attached is a screenshot of the example app running on Simulator (iPhone 6 iOS 10.3)

![simulator screen shot jul 28 2017 11 25 10 am](https://user-images.githubusercontent.com/8009289/28731133-8a3d68f0-7387-11e7-8569-dd8a44541631.png)

**Comment by apasccon** [comment]
It's because the keyboard is hidden. Just press Cmd+k in order to force it to appear and the dropdown will show.
