### ISSUE TITLE
Feature Request: SearchTextFieldItem as protocol or extendable class

### ISSUE THREAD

**Issue by btanner** [apasccon/SearchTextField#68]
I would really like to store some meta-data in the SearchTextFieldItems, so that I can access that data when the item is selected.

Example: mix suggestions from various sources, and then when the user clicks, immediately know the source.

Seems pretty straightforward to me :-)

**Comment by btanner** [comment]
Works great.  I cloned the repo to change struct -> class

:)

**Comment by btanner** [comment]
I think this will also solve the problems in #64 and #43 and leaves your code as simple as it is now.

**Comment by apasccon** [comment]
hey @btanner!, I made this change and updated to 1.1.7. Thanks for the suggestion!.

**Comment by btanner** [comment]
@apasccon  Doh!
Worked for me when I tested it in my code, but that's because it was not in a module for me. In a module, it must be an "open class" to be extensible.  Sorry!

**Comment by apasccon** [comment]
Fixed!
