### ISSUE TITLE
My popup will be overlay by Keyboard.

### ISSUE THREAD

**Issue by kevinlee85** [apasccon/SearchTextField#7]
My popup dialog will be overlay by Keyboard.
Do you know how to avoid this make the user easily input?

**Comment by apasccon** [comment]
Can you please show me an screenshot with the issue?. Thanks!

**Comment by kevinlee85** [comment]
![screen shot 2016-09-27 at 10 40 26 am](https://cloud.githubusercontent.com/assets/6616311/18858463/e15a284a-849e-11e6-97cb-d9cf88fa7469.png)

**Comment by chengsam** [comment]
@kevinlee85 This is the default behavior of iOS (the keyboard covering the textfield). You should adjust your content offset to move the textfield upwards or just third-party library like [this](https://github.com/hackiftekhar/IQKeyboardManager) to add the functionality.

**Comment by apasccon** [comment]
@kevinlee85, sorry for my late response. I totally agree with @chengsam. Did you have the chance to fix it this way?. You still think it can be fixed in any way?. If not feel free to close this issue please. Thanks!.
