### ISSUE TITLE
when i used two UITextField which is inherited from SearchTextField it will not show the search result in Xcode 9.0

### ISSUE THREAD

**Issue by kiraninfogird** [apasccon/SearchTextField#79]
Hello,
     I updated Xcode to 9.0 and I stuck with one new problem.

_**##  ex. when I search any city name is will not show me a drop-down list [as I install pod i.e. SearchTextField]. please help me to solved above problem?**_

After update done, I again install pod as per given on cocoapods website but still, I get the error.

but before updating Xcode it will be working fine, so what should I do now? Please, Help me...!

**Comment by apasccon** [comment]
Are you testing in the simulator?, is the keyboard shown? (Cmd+K)

**Comment by kiraninfogird** [comment]
Yes , when I press keyboard to search any [i.e. city] it was not shown me
any drop down but after 10 to 20 sec  [when working with other option [on
same UI I have date picker and time picker ] and then again come to find
any city[Search any city] then it will be working fine .]
Whats the problem I don't get? If possible, Please help me..!

Thanks for ans.

Thanks,
Kiran

**Comment by apasccon** [comment]
can you please share with me your ViewController's source code?

**Comment by kiraninfogird** [comment]
ok. I attached both UIViewController as well as its Related UITableViewCell.

now I am not available because my office timing is till 6:30 pm [Because I
used iMac] so I will reply your email in the morning if you have any query
related to me.

you check my code if any problem I am ready to change it.[As per your
instruction if required]

Thanks for the help.👍

Please find the attachment.

Thanks,
Kiran

**Comment by apasccon** [comment]
Where did you attached the files?, I can't see it.

**Comment by kiraninfogird** [comment]
Please check, I already attached files to the previous email.

Again I attached that boths files.

PFA.

**Comment by kiraninfogird** [comment]
Hi,
it is because of I am chatting with you by email not used directly by using git hub that way you are not unable to see that attachment.

Please find the attachment.

Thanks,
Kiran

[reapascconsearchtextfieldwheniusedtwouitextfieldw.zip](https://github.com/apasccon/SearchTextField/files/1361536/reapascconsearchtextfieldwheniusedtwouitextfieldw.zip)

**Comment by midhetfatema94** [comment]
Hi, The same thing is occuring with me too.. Will this issue be resolved soon? because I need it urgently.

**Comment by kiraninfogird** [comment]
not yet solved by them, I think now a days they are not working same git
hub library....!
@Midhet Sulemani, You should try for yourself, you will definitely get a
solution as you want...!

**Comment by midhetfatema94** [comment]
Hi @kiraninfogird, I have resolved the issue, so the configuration of the second text field should be in the first text field's "itemSelectionHandler" property. Also resign the first text field and make the second one the first responder like so:
`
 firstTF.resignFirstResponder()
 secondTF.becomeFirstResponder()
`
This should work fine. Try it and if it works, you can close this issue.

**Comment by apasccon** [comment]
Thanks for helping @midhetfatema94!, let me close the issue.

**Comment by kiraninfogird** [comment]
@Midhet Sulemani, Thanks..!
I will also check that, by the way, I was done that by my self but if you
do something new I will definitely implement that in my project.

Thanks....!


On Fri, Nov 24, 2017 at 6:09 PM, Alejandro Pasccon <notifications@github.com
