### ISSUE TITLE
Is possible to pass a hidden field in the SearchTextFieldItem like an user ID?

### ISSUE THREAD

**Issue by Rovel** [apasccon/SearchTextField#80]
Whats is the best way to pass a user id to a variable as people use SearchTextField, since SearchTextFieldItem has only 3 param, how can I pass a hidden param of find the user id comparing the SearchTextFieldItem to a User List = [Users]() or user the users list as a SearchTextFieldItem with hidden params.

**Comment by kamerc** [comment]
I had the same requirement. I extended SearchTextFieldItem and added an id attribute

**Comment by Rovel** [comment]
Is that extension shared in github or just in your project? I'm curious :)

I used array filter passing a unique atribute from the [SearchTextFieldItem](), in the complete [Users]() like a user email

let filteredUser = userArray.filter{ $0.userEmail == item.subtitle }

**Comment by kamerc** [comment]
`class MySearchTextFieldItem: SearchTextFieldItem {
    public var id: Int?
    
    public init(title: String, subtitle: String?, id: Int?) {
        super.init(title: title)
        self.title = title
        self.subtitle = subtitle
        self.id = id
    }
    
}`

then use MySearchTextFieldItem in your code where you would have used SearchTextFieldItem

**Comment by Rovel** [comment]
Thanks!

**Comment by Milap-Kundalia** [comment]
@kamerc Thanks for the solution but how can I access the ID in selection call back. itemSelectionHandler returns me the custom models but it is not returning the ID in that
