### ISSUE TITLE
Xcode 9 errors

### ISSUE THREAD

**Issue by arashetm** [apasccon/SearchTextField#81]
*Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
*Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
*Cannot convert value of type '[NSAttributedStringKey : AnyObject]' (aka 'Dictionary<NSString, AnyObject>') to expected argument type '[String : Any]?'

**Comment by pooja-gaikwad15** [comment]
@arashetm you need to rollback to the version that supports your project's swift version.. can be found in setting-> swift language version. This errors are because NSAttributedStringKey was introduced in Swift 4.

**Comment by Adarkas2302** [comment]
I have the same problem but i got swift language version 3.2 in my settings. Is it because i have Xcode 9.1?

**Comment by Adarkas2302** [comment]
i have resolved my issue
