### ISSUE TITLE
How to stop suggestions for one textfield

### ISSUE THREAD

**Issue by pradeepispv** [apasccon/SearchTextField#84]
Hi 

I am using textfield for one bool is for suggestion mode and another one is free type mode.
How to stop suggestions and stop the list not to show?
I tried hiding , visible properties but no use.

Can you suggest how to get this?

**Comment by apasccon** [comment]
I guess that your best alternative is to clear the suggestions list:
`myTextField.filterItems([])`

**Comment by mBilal5674** [comment]
How to get list while user typing that returned in list
