### ISSUE TITLE
use of unresolved identifier NSAttributedStringKey

### ISSUE THREAD

**Issue by muga87** [apasccon/SearchTextField#87]
Hi i am using swift 3
But getting message  use of unresolved identifier NSAttributedStringKey when i run the code.
I have used manual integration. Just imported your .swift file
Plase help 

Thanks

**Comment by faulknerwn** [comment]
I have the same errors.  Using the latest version of xcode/swift 4.0  - I imported it using pods.  It also says "Use of unresolved identifier void".

**Comment by Adarkas2302** [comment]
@muga87 you have the Version of SearchTextField witch is coded with Swift 4. And die NSAttributedStringKey was added in Swift 4. 
So either you convert your code to swift 4 or you get the SearchTextField start is coded with swift 3.

**Comment by Adarkas2302** [comment]
@faulknerwn where do you get this error?

**Comment by muga87** [comment]
@Adarkas2302, thanks for reply. where can i get swift 3 code of searchTextFiled?

**Comment by apasccon** [comment]
@muga87, you can use any release prior to 1.2.0 in order to get swift 3 code (sorry for the delay). If it helps please feel free to close the issue.

**Comment by muga87** [comment]
@apasccon , Sorry to asking like this, i don't know how to get 1.2.0. where can i get that version

**Comment by Adarkas2302** [comment]
Simple, when you are in the code view here on GitHub just select releases and download the desired version as zip.

**Comment by muga87** [comment]
Thank you
