### ISSUE TITLE
Installation with cocoapods - downloading old version of pod

### ISSUE THREAD

**Issue by Janoz94** [apasccon/SearchTextField#92]
Hi, I'm not sure is it good place to report error like that but when I'm adding this project to my podfile without version setting it downloads SearchTextField (1.1.2) and when I specify version to 1.2 I get error like that: "None of your spec sources contain a spec satisfying the dependency: `SearchTextField (~> 1.2)`.". 
I would be glad if You can help me.

Greetings,
John

**Comment by faulknerwn** [comment]
Oh!  That explains why I got a million errors when I tried to install it.  I ran a pod update and then it worked!
